Importing the Dependencies

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:

credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
79313,57966,-0.527571,-3.483241,-0.206444,-0.583181,-2.067419,-0.129826,0.454118,-0.149176,1.863281,...,0.691203,0.224470,-0.875993,0.204226,0.079542,0.029189,-0.109220,0.178251,912.79,0.0
79314,57966,-0.541422,1.341092,0.576882,0.733835,0.259657,-0.233639,0.712069,0.190731,-1.067355,...,0.189997,0.493842,-0.141807,-0.406546,-0.043605,-0.287510,0.045194,0.100293,49.33,0.0
79315,57966,-0.830218,0.971781,0.974916,-1.348723,-0.230572,-0.778253,0.395464,0.109896,0.234581,...,-0.115767,-0.335950,-0.068152,-0.109514,-0.204347,0.703500,-0.383530,-0.223780,14.60,0.0
79316,57966,1.104838,-1.141651,0.942113,-0.661271,-1.591229,-0.056758,-1.192570,0.275125,-0.447900,...,0.508825,1.146845,-0.117753,0.241582,0.212189,-0.054096,0.023744,0.026206,99.00,0.0
79317,57967,-3.560685,3.485801,-0.070146,2.191571,-0.429913,1.075498,-0.935968,-2.147517,-1.165398,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79318 entries, 0 to 79317
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    79318 non-null  int64
 1   V1      79318 non-null  float64
 2   V2      79318 non-null  float64
 3   V3      79318 non-null  float64
 4   V4      79318 non-null  float64
 5   V5      79318 non-null  float64
 6   V6      79318 non-null  float64
 7   V7      79318 non-null  float64
 8   V8      79318 non-null  float64
 9   V9      79318 non-null  float64
 10  V10     79318 non-null  float64
 11  V11     79317 non-null  float64
 12  V12     79317 non-null  float64
 13  V13     79317 non-null  float64
 14  V14     79317 non-null  float64
 15  V15     79317 non-null  float64
 16  V16     79317 non-null  float64
 17  V17     79317 non-null  float64
 18  V18     79317 non-null  float64
 19  V19     79317 non-null  float64
 20  V20     79317 non-null  float64
 21  V21     79317 non-null  float64
 22  V22     79317 non-null  float64
 23  V23     79317 non-null  float64
 24  V24     79317 non-null  float64
 25  V25     79317 non-null  float64
 26  V26     79317 non-null  float64
 27  V27     79317 non-null  float64
 28  V28     79317 non-null  float64
 29  Amount  79317 non-null  float64
 30  Class   79317 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 18.8 MB

In [6]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
credit_card_data['Class'].value_counts()

Class
0.0    79126
1.0      191
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [8]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(79126, 31)
(191, 31)

In [10]:
legit.Amount.describe()

count    79126.000000
mean        97.773259
std        269.765878
min          0.000000
25%          7.700000
50%         26.925000
75%         89.000000
max      19656.530000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     191.000000
mean       95.142251
std       214.122813
min         0.000000
25%         1.000000
50%         7.520000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [12]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,37164.532164,-0.241928,-0.047016,0.701122,0.152361,-0.264869,0.100851,-0.097874,0.046041,0.000222,...,0.041575,-0.030941,-0.105670,-0.037430,0.007877,0.134383,0.026147,0.000715,0.002542,97.773259
1.0,32448.565445,-6.660361,4.685496,-8.847226,5.220761,-4.885698,-2.012799,-7.016277,3.141649,-3.135469,...,0.378115,0.779382,-0.158471,-0.220629,-0.091717,0.237570,0.096534,0.586070,0.053246,95.142251

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 191

In [13]:
legit_sample = legit.sample(n=191)

Concatenating two DataFrames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
65973,51830,-2.477122,-1.466097,2.969828,2.841984,2.533378,-1.257174,-1.020899,-0.179079,-0.636721,...,0.090232,0.624412,-0.507834,0.462657,0.064762,0.190779,-0.165573,-0.328777,10.62,0.0
40188,40130,1.170411,-0.037950,0.962122,1.014718,-0.417433,0.643186,-0.616644,0.239841,0.548010,...,-0.056393,0.056788,-0.135563,-0.498824,0.532171,-0.376249,0.073582,0.021521,9.99,0.0
4200,3750,-1.288772,-1.003115,1.793824,-1.815286,0.942299,-1.674536,-0.414740,-0.329000,0.567564,...,-0.134250,-0.133238,0.043680,0.313827,-0.927038,-0.982409,-0.037919,-0.059862,17.88,0.0
383,282,-0.356466,0.725418,1.971749,0.831343,0.369681,-0.107776,0.751610,-0.120166,-0.420675,...,0.020804,0.424312,-0.015989,0.466754,-0.809962,0.657334,-0.043150,-0.046401,0.00,0.0
47744,43340,-2.441723,1.650115,-0.062564,1.177690,-0.652926,0.485198,-0.134157,1.202037,-0.362784,...,-0.046404,0.302937,0.114179,-0.292043,0.110545,-0.244353,-0.063822,-0.143085,62.39,0.0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
76929,56806,0.016828,2.400826,-4.220360,3.462217,-0.624142,-1.294303,-2.986028,0.751883,-1.606672,...,0.285832,-0.771508,-0.265200,-0.873077,0.939776,-0.219085,0.874494,0.470434,1.00,1.0
77099,56887,-0.075483,1.812355,-2.566981,4.127549,-1.628532,-0.805895,-3.390135,1.019353,-2.451251,...,0.794372,0.270471,-0.143624,0.013566,0.634203,0.213693,0.773625,0.387434,5.00,1.0
77348,57007,-1.271244,2.462675,-2.851395,2.324480,-1.372245,-0.948196,-3.065234,1.166927,-2.268771,...,0.652941,0.081931,-0.221348,-0.523582,0.224228,0.756335,0.632800,0.250187,0.01,1.0
77387,57027,-2.335655,2.225380,-3.379450,2.178538,-3.568264,0.316814,-1.734948,1.449139,-1.980033,...,0.785540,0.297412,0.308536,-0.598416,-0.121850,-0.491018,0.701606,0.206966,444.17,1.0
77682,57163,-10.363049,4.543672,-9.795898,5.508003,-6.037156,-0.133493,-11.724346,-3.198346,-4.767842,...,-2.457145,1.687257,0.977178,-0.543369,-0.289125,-0.107586,0.330642,0.163577,1.00,1.0

In [17]:
new_dataset['Class'].value_counts()

Class
0.0    191
1.0    191
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,37603.115183,-0.234024,-0.063999,0.906342,0.332893,-0.389794,0.197496,-0.089153,0.068049,0.115625,...,0.097268,-0.063112,-0.040152,-0.121494,-0.015310,0.145815,0.076653,-0.035281,-0.015342,114.614817
1.0,32448.565445,-6.660361,4.685496,-8.847226,5.220761,-4.885698,-2.012799,-7.016277,3.141649,-3.135469,...,0.378115,0.779382,-0.158471,-0.220629,-0.091717,0.237570,0.096534,0.586070,0.053246,95.142251

Splitting the data into Features & Targets

In [37]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [38]:
print(X)

        Time         V1        V2        V3        V4        V5        V6  \
65973  51830  -2.477122 -1.466097  2.969828  2.841984  2.533378 -1.257174
40188  40130   1.170411 -0.037950  0.962122  1.014718 -0.417433  0.643186
4200    3750  -1.288772 -1.003115  1.793824 -1.815286  0.942299 -1.674536
383      282  -0.356466  0.725418  1.971749  0.831343  0.369681 -0.107776
47744  43340  -2.441723  1.650115 -0.062564  1.177690 -0.652926  0.485198
...      ...        ...       ...       ...       ...       ...       ...
76929  56806   0.016828  2.400826 -4.220360  3.462217 -0.624142 -1.294303
77099  56887  -0.075483  1.812355 -2.566981  4.127549 -1.628532 -0.805895
77348  57007  -1.271244  2.462675 -2.851395  2.324480 -1.372245 -0.948196
77387  57027  -2.335655  2.225380 -3.379450  2.178538 -3.568264  0.316814
77682  57163 -10.363049  4.543672 -9.795898  5.508003 -6.037156 -0.133493

              V7        V8        V9  ...       V20       V21       V22  \
65973  -1.020899 -0.179079 -0.636721  ... -0.054438  0.090232  0.624412
40188  -0.616644  0.239841  0.548010  ... -0.033025 -0.056393  0.056788
4200   -0.414740 -0.329000  0.567564  ... -0.295203 -0.134250 -0.133238
383     0.751610 -0.120166 -0.420675  ... -0.133602  0.020804  0.424312
47744  -0.134157  1.202037 -0.362784  ... -0.091602 -0.046404  0.302937
...          ...       ...       ...  ...       ...       ...       ...
76929  -2.986028  0.751883 -1.606672  ...  0.590418  0.285832 -0.771508
77099  -3.390135  1.019353 -2.451251  ...  0.338598  0.794372  0.270471
77348  -3.065234  1.166927 -2.268771  ...  0.560478  0.652941  0.081931
77387  -1.734948  1.449139 -1.980033  ...  0.274027  0.785540  0.297412
77682 -11.724346 -3.198346 -4.767842  ...  0.924396 -2.457145  1.687257

            V23       V24       V25       V26       V27       V28  Amount
65973 -0.507834  0.462657  0.064762  0.190779 -0.165573 -0.328777   10.62
40188 -0.135563 -0.498824  0.532171 -0.376249  0.073582  0.021521    9.99
4200   0.043680  0.313827 -0.927038 -0.982409 -0.037919 -0.059862   17.88
383   -0.015989  0.466754 -0.809962  0.657334 -0.043150 -0.046401    0.00
47744  0.114179 -0.292043  0.110545 -0.244353 -0.063822 -0.143085   62.39
...         ...       ...       ...       ...       ...       ...     ...
76929 -0.265200 -0.873077  0.939776 -0.219085  0.874494  0.470434    1.00
77099 -0.143624  0.013566  0.634203  0.213693  0.773625  0.387434    5.00
77348 -0.221348 -0.523582  0.224228  0.756335  0.632800  0.250187    0.01
77387  0.308536 -0.598416 -0.121850 -0.491018  0.701606  0.206966  444.17
77682  0.977178 -0.543369 -0.289125 -0.107586  0.330642  0.163577    1.00

[382 rows x 30 columns]

In [21]:
print(Y)

65973    0.0
40188    0.0
4200     0.0
383      0.0
47744    0.0
        ...
76929    1.0
77099    1.0
77348    1.0
77387    1.0
77682    1.0
Name: Class, Length: 382, dtype: float64

Split the data into Training data & Testing Data

In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(382, 30) (305, 30) (77, 30)

Model Training

Logistic Regression

In [33]:
model = LogisticRegression()

In [40]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [41]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [42]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9770491803278688

In [43]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [44]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.922077922077922